//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.10 at 10:14:32 AM MSK 
//


package by.bsuir.userhibernate.entity;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "Citizenship")
@XmlEnum
public enum Citizenship {

    @XmlEnumValue("belorussian")
    BELORUSSIAN,
    @XmlEnumValue("russian")
    RUSSIAN,
    @XmlEnumValue("ukrainian")
    UKRAINIAN,
    @XmlEnumValue("polish")
    POLISH,
    @XmlEnumValue("lithuanian")
    LITHUANIAN;

}
